apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: letsencrypt@tomalias.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          route53:
            region: eu-west-1
            accessKeyIDSecretRef:
              name: route-53-credentials
              key: access-key
            secretAccessKeySecretRef:
              name: route-53-credentials
              key: secret-access-key
        selector:
          dnsZones:
            - "tomalias.com"