apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homepage
  namespace: default
spec:
  interval: 1m0s
  chart:
    spec:
      chart: homepage
      sourceRef:
        kind: HelmRepository
        name: jameswynn
      version: 1.2.3
  values:
    image:
      repository: ghcr.io/benphelps/homepage
      tag: v0.6.0
    enableRbac: true
    serviceAccount:
      name: homepage
      create: true
    service:
      main:
        ports:
          http:
            port: 3000
    controller:
      strategy: RollingUpdate
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
    ingress:
      main:
        enabled: true
        labels:
          gethomepage.dev/enabled: "true"
        annotations:
          gethomepage.dev/name: "Home"
          gethomepage.dev/group: "Applications"
          gethomepage.dev/icon: "homepage.png"
        ingressClassName: "traefik"
        hosts:
          - host: &host "home.kevin.tomalias.com"
            paths:
              - path: /
                pathType: Prefix
    config:
      bookmarks:
        - Bookmarks:
          - GitHub:
            - abbr: GH
              href: https://github.com/tom-elvidge
          - Proton:
            - abbr: PM
              href: https://mail.proton.me/u/0/inbox
          - YouTube:
            - abbr: YT
              href: https://www.youtube.com
      services:
        - Infrastructure:
          - Unifi:
              href: http://192.168.1.1
              icon: unifi.png
          - TrueNAS:
              href: http://10.1.5.10
              icon: truenas.png
          - Proxmox:
              href: http://10.1.5.3:8006
              icon: proxmox.png
          - iDRAC:
              href: https://10.1.5.80
              icon: idrac.png
          - Pi-Hole:
              href: http://10.1.5.2:8088/admin
              icon: pi-hole.png
        - Kubernetes:
          - Traefik:
              href: https://traefik.kevin.tomalias.com
              icon: traefik.png
      widgets:
        - resources:
            backend: 'kubernetes'
            expanded: true
            cpu: true
            memory: true
        - search:
            provider: duckduckgo
            target: _blank
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: 'cluster'
            nodes:
              show: false
              cpu: true
              memory: true
              showLabel: true
      kubernetes:
        mode: 'cluster'
      docker:
      settings:
    persistence:
      logs:
        enabled: true
        type: emptyDir
        mountPath: /app/config/logs