apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  chart:
    spec:
      chart: kevin-base
      sourceRef:
        kind: HelmRepository
        name: tom-elvidge
      version: 0.2.0
  values:
    replicaCount: 1
    containers:
      - name: main
        image:
          repository: jellyfin/jellyfin
          pullPolicy: IfNotPresent
          tag: "10.8.11"
        securityContext: {}
        resources: {}
        volumeMounts:
          - name: media
            mountPath: /media
          - name: config
            mountPath: /config
          - name: cache
            mountPath: /cache
    imagePullSecrets: []
    nameOverride: "jellyfin"
    fullnameOverride: "jellyfin"
    serviceAccount:
      create: true
      automount: true
      annotations: {}
      name: ""
    podAnnotations: {}
    podLabels: {}
    podSecurityContext: {}
    service:
      type: ClusterIP
      port: 8096
    ingress:
      annotations:
        gethomepage.dev/href: https://jellyfin.kevin.tomalias.com
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: Jellyfin
        gethomepage.dev/description: "A media server"
        gethomepage.dev/group: Media
        gethomepage.dev/icon: jellyfin.png
        gethomepage.dev/widget.type: jellyfin
        gethomepage.dev/widget.url: https://jellyfin.kevin.tomalias.com
        gethomepage.dev/widget.key: 66a042fd8bc044afbeb20258d6d4e897
        kubernetes.io/ingress.class: traefik-external
      routes:
        - match: Host(`jellyfin.kevin.tomalias.com`)
          kind: Rule
      tls:
        secretName: tomalias-com-tls
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
    volumes:
      - name: media
        nfs:
          server: 192.168.4.2
          path: /mnt/wdred/media
      - name: config
        persistentVolumeClaim:
          claimName: jellyfin-config-claim
      - name: cache
        persistentVolumeClaim:
          claimName: jellyfin-cache-claim
    nodeSelector: {}
    tolerations: []
    affinity: {}
    persistentVolumeClaims:
      - name: jellyfin-config-claim
        accessModes:
          - ReadWriteOnce
        storage: 512Mi
      - name: jellyfin-cache-claim
        accessModes:
          - ReadWriteOnce
        storage: 5Gi
  interval: 1m0s