apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: smarthome
spec:
  interval: 1m0s
  chart:
    spec:
      chart: kevin-base
      sourceRef:
        kind: HelmRepository
        name: tom-elvidge
      version: 0.4.3
  values:
    replicaCount: 1
    containers:
      - name: main
        image:
          repository: homeassistant/home-assistant
          pullPolicy: IfNotPresent
          tag: "2023.12"
        securityContext: {}
        resources: {}
        volumeMounts:
          - name: config
            mountPath: /config
        ports:
          - name: http
            port: 8123
            protocol: TCP
    imagePullSecrets: []
    nameOverride: "homeassistant"
    fullnameOverride: "homeassistant"
    serviceAccount:
      create: true
      automount: true
      annotations: {}
      name: ""
    podAnnotations: {}
    podLabels: {}
    podSecurityContext: {}
    service:
      type: ClusterIP
    ingress:
      enabled: true
      annotations:
        gethomepage.dev/href: https://homeassistant.kevin.tomalias.com
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: Home Assistant
        gethomepage.dev/group: Applications
        gethomepage.dev/icon: home-assistant.png
      ingressClassName: "traefik"
      host: "homeassistant.kevin.tomalias.com"
      path: /
      pathType: Prefix
      portName: http
      tlsSecretName: tomalias-com-tls
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
    volumes:
      - name: config
        persistentVolumeClaim:
          claimName: homeassistant-config-claim
    nodeSelector: {}
    tolerations: []
    affinity: {}
    persistentVolumeClaims:
      - name: homeassistant-config-claim
        accessModes:
          - ReadWriteOnce
        storage: 2Gi
    probes:
      enabled: true
      portName: http