apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: smarthome
spec:
  interval: 1m0s
  chart:
    spec:
      chart: kevin-base
      sourceRef:
        kind: HelmRepository
        name: tom-elvidge
      version: 0.4.3
  values:
    replicaCount: 1
    containers:
      - name: main
        image:
          repository: eclipse-mosquitto
          pullPolicy: IfNotPresent
          tag: "2.0"
        securityContext: {}
        resources: {}
        args: ["mosquitto", "-c", "/mosquitto-no-auth.conf"]
        ports:
          - name: listen
            port: 1883
            protocol: TCP
    imagePullSecrets: []
    nameOverride: "mosquitto"
    fullnameOverride: "mosquitto"
    serviceAccount:
      create: true
      automount: true
      annotations: {}
      name: ""
    podAnnotations: {}
    podLabels: {}
    podSecurityContext: {}
    service:
      type: LoadBalancer
      loadBalancerIP: "10.1.5.42"
      externalTrafficPolicy: Cluster
    ingress:
      enabled: false
    autoscaling:
      enabled: false
    probes:
      enabled: false
    nodeSelector: {}
    tolerations: []
    affinity: {}