---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    # The server is replaced in /clusters/production/infrastructure.yaml
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: me@tomalias.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          route53:
            region: eu-west-1
            accessKeyIDSecretRef:
              name: route-53-credentials
              key: access-key
            secretAccessKeySecretRef:
              name: route-53-credentials
              key: secret-access-key
        selector:
          dnsZones:
            - "tomalias.com"