---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik
  namespace: traefik
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - traefik
  routes:
    - match: Host(`traefik.kevin.tomalias.com`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
  tls:
   secretName: tomalias-com-tls
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-dashboard
  namespace: longhorn-system
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn.kevin.tomalias.com`)
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 80
  tls:
   secretName: tomalias-com-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weave-gitops
  namespace: longhorn-system
spec:
  ingressClassName: "traefik"
  rules:
    - host: weave-gitops.kevin.tomalias.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: weave-gitops
                port:
                  number: 9091
  tls:
    - hosts:
        - weave-gitops.kevin.tomalias.com
      secretName: tomalias-com-tls