---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik
  namespace: traefik
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - traefik
  routes:
    - match: Host(`traefik.kevin.tomalias.com`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
  tls:
   secretName: tomalias-com-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-dashboard
  namespace: longhorn-system
  annotations:
    gethomepage.dev/href: https://longhorn.kevin.tomalias.com
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Longhorn
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/icon: longhorn.png
spec:
  ingressClassName: "traefik"
  rules:
    - host: longhorn.kevin.tomalias.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80
  tls:
    - hosts:
        - longhorn.kevin.tomalias.com
      secretName: tomalias-com-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weave-gitops
  namespace: flux-system
  annotations:
    gethomepage.dev/href: https://weave-gitops.kevin.tomalias.com
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Flux
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/icon: flux-cd.png
spec:
  ingressClassName: "traefik"
  rules:
    - host: weave-gitops.kevin.tomalias.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: weave-gitops
                port:
                  number: 9001
  tls:
    - hosts:
        - weave-gitops.kevin.tomalias.com
      secretName: tomalias-com-tls