---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
---
apiVersion: v1
kind: Secret
metadata:
  name: route-53-credentials
  namespace: cert-manager
type: Opaque
stringData:
  access-key: secret
  secret-access-key: secret